name: Compil

on: [push]

jobs:
  compil-check-job-run:
    runs-on: ubuntu-latest

    outputs:
      workflows: ${{ steps.filter.outputs.workflows }}
      src: ${{ steps.filter.outputs.src }}
      make: ${{ steps.filter.outputs.make }}
      combined: ${{ steps.filter.outputs.workflows == 'true' || steps.filter.outputs.src == 'true' || steps.filter.outputs.make == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check modified files need re run
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            workflows:
              - '.github/workflows/**'
            src:
              - '*.hs'
            cmake:
              - 'Makefile'

  compil-windows:
    runs-on: windows-latest
    needs: [compil-check-job-run]
    if: needs.compil-check-job-run.outputs.combined

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Install dependencies
        run: ./scripts/InstallDepsWindows.ps1

      - name: Compil
        run: make

  compil-linux:
    runs-on: ubuntu-latest
    needs: [compil-check-job-run]
    if: needs.compil-check-job-run.outputs.combined

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Install dependencies
        run: sudo ./scripts/InstallDepsLinux.bash

      - name: Compil
        run: make

  compil-macos:
    runs-on: macos-latest
    needs: [compil-check-job-run]
    if: needs.compil-check-job-run.outputs.combined

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Install dependencies
        run: ./scripts/InstallDepsMacOS.zsh

      - name: Compil
        run: make
